# golangci-lint v2 configuration
run:
  tests: true           # include _test.go files
  skip-dirs:
    - vendor            # skip vendor directory
  skip-files:
    - generated.go       # skip generated files

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - structcheck
    - typecheck

issues:
  exclude-use-default: false
  max-same-issues: 3
  max-issues-per-linter: 0
  max-issues: 0
  exclude:
    - "Error return value of .+ is not checked"  # example exclusion
