name: Go Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - '**.go'

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Go (use your real project version here)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # 4️⃣ Run golangci-lint using official GitHub Action
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5.0  # latest stable version as of Sep 2025
          install-mode: binary
          args: --timeout=5m
          only-new-issues: false
          skip-cache: false
          skip-save-cache: false

